---
# Copyright 2015, Jean-Philippe Evrard <jean-philippe@evrard.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Creating a scripts folder
  file:
    path: "{{ zabbix_agent_scripts_folder }}"
    state: directory
    mode: "0755"
  tags:
    - zabbix-agent-check-scripts

- name: Install package requirements for the templated check scripts
  apt:
    name: "{{ item.1 }}"
    state: present
  with_subelements:
    - zabbix_agent_template_scripts
    - pkg_requirements
#uncomment the following line  when ansible2 is released
#    - skip_missing: True
  tags:
    - zabbix-agent-template-scripts
    - zabbix-agent-package-requirements

- name: Install pip requirements for the templated check scripts
  pip:
    name: "{{ item.1 }}"
  with_subelements:
    - zabbix_agent_template_scripts
    - pip_requirements
#uncomment the following line when ansible2 is released
#    - skip_missing: True
  tags:
    - zabbix-agent-template-scripts
    - zabbix-agent-pip-requirements

- name: Templating the additional check scripts
  template:
    src: "{{ item.script_src }}"
    dest: "{{ item.script_dst }}"
    mode: "{{ item.script_mode | default('0750') }}"
    owner:  "{{ item.owner | default('zabbix') }}"
  with_items: zabbix_agent_template_scripts | default([])
  notify:
    - restart zabbix-agent
  tags:
    - zabbix-agent-template-scripts

- name: Update the cronjob with the optional templated check scripts
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.cron_minute | default('*') }}"
    hour: "{{ item.cron_hour | default('*') }}"
    day: "{{ item.cron_day | default('*') }}"
    weekday: "{{ item.cron_weekday | default('*') }}"
    month: "{{ item.cron_month | default('*') }}"
    job: "{{ item.cron_job | default(item.script_dst) }}"
    user: "{{ item.owner | default('zabbix') }}"
    state: present
  with_items: zabbix_agent_template_scripts | default([])
  when:
    - item.use_cron is defined
    - item.use_cron | bool
  tags:
    - zabbix-agent-template-scripts
    - zabbix-agent-cronjobs
